#!/usr/bin/env bash

set -e

cargo nextest run --run-ignored all tests::books

cp books/cargo/src/doc/book/pdf/book.pdf rendered-cargo-book.pdf
cp books/mdBook/guide/book/pdf/book.pdf rendered-mdBook-guide.pdf
cp books/nomicon/book/pdf/book.pdf rendered-nomicon.pdf
cp books/rust-book/book/pdf/book.pdf rendered-rust-book.pdf
cp books/rust-by-example/book/pdf/book.pdf rendered-rust-by-example.pdf
cp books/rust-edition-guide/book/pdf/book.pdf rendered-rust-edition-guide.pdf
cp books/rust-embedded/book/pdf/book.pdf rendered-rust-embedded.pdf
cp books/rust-reference/book/pdf/book.pdf rendered-rust-reference.pdf
cp books/rustc-dev-guide/book/pandoc/pdf/book.pdf rendered-rustc-dev-guide.pdf
