#!/usr/bin/env bash

set -e

# Use xelatex when building books since texlive-luatex is missing lua-ul.sty on Ubuntu 20.04,
# which cargo-dist uses for its runner
PDF_ENGINE=xelatex cargo nextest run --no-fail-fast || true

cp books/cargo/src/doc/book/pdf/book.pdf rendered-cargo-book.pdf
cp books/mdBook/guide/book/pdf/book.pdf rendered-mdBook-guide.pdf
cp books/nomicon/book/pdf/book.pdf rendered-nomicon.pdf
cp books/rust-book/book/pdf/book.pdf rendered-rust-book.pdf
cp books/rust-by-example/book/pdf/book.pdf rendered-rust-by-example.pdf
cp books/rust-edition-guide/book/pdf/book.pdf rendered-rust-edition-guide.pdf
cp books/rust-embedded/book/pdf/book.pdf rendered-rust-embedded.pdf
cp books/rust-reference/book/pdf/book.pdf rendered-rust-reference.pdf
# Currently fails to build
# cp books/rustc-dev-guide/book/pdf/book.pdf rendered-rustc-dev-guide.pdf
