#!/usr/bin/env bash

set -e

# Use xelatex when building books since texlive-luatex is missing lua-ul.sty on Ubuntu 20.04,
# which cargo-dist uses for its runner
PDF_ENGINE=xelatex cargo nextest run --no-fail-fast || true

cp books/cargo/src/doc/book/pdf/book.pdf cargo-book.pdf
cp books/mdBook/guide/book/pdf/book.pdf mdBook-guide.pdf
cp books/nomicon/book/pdf/book.pdf nomicon.pdf
cp books/rust-book/book/pdf/book.pdf rust-book.pdf
cp books/rust-by-example/book/pdf/book.pdf rust-by-example.pdf
cp books/rust-edition-guide/book/pdf/book.pdf rust-edition-guide.pdf
cp books/rust-embedded/book/pdf/book.pdf rust-embedded.pdf
cp books/rust-reference/book/pdf/book.pdf rust-reference.pdf
cp books/rustc-dev-guide/book/pdf/book.pdf rustc-dev-guide.pdf
