#!/usr/bin/env bash

set -e

cp books/cargo/src/doc/book/pdf/book.pdf cargo-book.pdf
cp books/mdBook/guide/book/pdf/book.pdf mdBook-guide.pdf
cp books/nomicon/book/pdf/book.pdf nomicon.pdf
cp books/rust-book/book/pdf/book.pdf rust-book.pdf
cp books/rust-by-example/book/pdf/book.pdf rust-by-example.pdf
cp books/rust-edition-guide/book/pdf/book.pdf rust-edition-guide.pdf
cp books/rust-embedded/book/pdf/book.pdf rust-embedded.pdf
cp books/rust-reference/book/pdf/book.pdf rust-reference.pdf
cp books/rustc-dev-guide/book/pdf/book.pdf rustc-dev-guide.pdf
