#!/usr/bin/env bash

set -e

# Update apt package lists
sudo apt-get update

# cargo-nextest
curl -LsSf https://get.nexte.st/0.9/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

# Pandoc
curl -LsSf https://github.com/jgm/pandoc/releases/download/3.1.11/pandoc-3.1.11-linux-amd64.tar.gz | tar zxf -
echo "$PWD/pandoc-3.1.11/bin" >> $GITHUB_PATH
export PATH="$PWD/pandoc-3.1.11/bin:$PATH"

# rsvg-convert (SVG support)
sudo apt-get install -y librsvg2-bin

# TeX Live and fonts
sudo apt-get install -y texlive texlive-luatex texlive-lang-cjk texlive-fonts-extra fonts-font-awesome fonts-noto

# mdBook preprocessors needed by example books
cargo install mdbook-i18n-helpers --locked
